spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

spring.jpa.show-sql: false
logging.level.root: INFO

# 工行支付网关配置
gateway:
  icbc:
    env: local
    app-id: ${ICBC_APP_ID:11000000000000079872}
    mer-id: ${ICBC_MER_ID:020004161912}
    mer-prtcl-no: ${ICBC_MER_PRTL_NO:0200041619120201}
    private-key: ${ICBC_PRIVATE_KEY:MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCcuLg1/44hdfA6bnj46U9gq8BqguKGmveGS6Fne4qa5Idk4BjMn6KII3gpAEw85EI75OVF2S+uEOlIXBkeuwPEliMbpKZ1BiXyfSryEmi4gUk6JEPrHE6bzWBvyTtr3ff5Cp1jB7EXQ3aOYSE6R2gBVrnODifpAXSONFYywHy8W/OPNga4MhEyJ0rD1CMtU8MNc/0zTcDXLBJ+WJN7kUlwdrnAd1IPOXYhCCEzMeB1NpQVV1SqxOADEUMJOrKmbXX/2Jal6HfuyNXZ6V9pCL5FucTgCyiXg0tIyPMOxjlsVDWSSadQeRB9gU/m1vcbM5DdkBOaBw4JmxAFgd3RqPKdAgMBAAECggEAAlYAgjwzu/ecOTVnU90fuUL7bxBSBwvtROZWBWBX3F+BTcrHToQnRzHcJc74KUTaYIvUsln+i3DQwVWEwaqrmjUGA0X3fdwLGcEC2wZ/jWx5O8bJml9azpiyPMhPke0w4oM60vyM3QS853oMJZMQj6CMIXBK6P6uuZCPI6+Edxw+ccosIY6f9t3oypRgsUM8QPhOmjCIl4kN0/U9DEdHQ2OgE/suUGt5NYPlyFqf1aHn2T+l7XsFhluezbMIHruFTVXr/S+EHx0Hs6fHUZtwwEVm2dsZBZzpt6LuzWD/uM6hDrWLoheU36ikT8Obsl0Bv7VnzcrILWSO0NMgBG9iEwKBgQDQfGD4CTsDHrUR+6xH8fZy0v9LxunIm8xXOo2mnG4tbNJfYSrfW+/nww0FXiK+IWDAXMyKxKS/ExjlaLgvQ5T2BDyMuUbsxi/a7XT3feC8B+WTMkixu+qbM7nZUb3oBMEcySw8ZP2x4JORXCKPBGNh5iMb1LuqjJYrUAslKTDdkwKBgQDAcEYTFBnnpBlWktLUjlQ5VKWjRb45HsUaAB4AFfSf4SpHsZCYt8xW8SZQ7FILPdh/Ezg70pIg1oLfLmCUIhPDPeYIUuGVTT9xoxRzb5vs08fum7vbcB7ef+arljXvhzF3kReP94ZMVgjKAp+VCrRf36rxx1Mr4ikiuC/1tHaNDwKBgEQMhN4QrTlMeY+AFPB6spUx93A1YbM/3weNrhR2tKORBG1rWsIC0SBVktdwrWhfnqPK5lxY6OkRA6xFbPDIX0OZiGXqR5Ma8R3FKctqQ8M71Jwh6oZQrrevv3aGbrTfcGTD6PNhh0ja42+rogAKT6Hxqv33hrWZI57Jhom/kxqPAoGASZTkhnkCKrtpYNwFN3cwpzdBmnuZb7ffP8DZt8itX9C13PH9SxfET14n+3tRJ7E/Ld/Ieb9bVqkPI41VKm8ZRWdOpNIkJXWDE816jWUYpuaXpRnxK8fkVclsByIJf4wfEwvsiYTo2hlvhOaZ5GBSdfJNJ+PCXp48gmURGY8mYWsCgYA7kVzsEzT4MRzA6CQbWaj82hDaVlU26i2Wsw+5lkMImKxwMPuJyz8CBjbm0mEE6ZMfQCIwndBfp16uhJHuW9M6kJipGxiS/OGsZhIJnrNDuYHiVzT6dyKFybyCij7DbzaRgZ5dPOiQVGgFcWZjFxasDytni/k76zgoqOyaDtDpfg==}
    public-key: ${ICBC_PUBLIC_KEY:MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCMpjaWjngB4E3ATh+G1DVAmQnIpiPEFAEDqRfNGAVvvH35yDetqewKi0l7OEceTMN1C6NPym3zStvSoQayjYV+eIcZERkx31KhtFu9clZKgRTyPjdKMIth/wBtPKjL/5+PYalLdomM4ONthrPgnkN4x4R0+D4+EBpXo8gNiAFsNwIDAQAB}
    notify-base-url: ${ICBC_NOTIFY_BASE_URL:http://localhost:8081}
    payment-url: ${ICBC_PAYMENT_URL:https://gw.open.icbc.com.cn/api/cardbusiness/qrcode/consumption/V1}
    payment-query-url: ${ICBC_PAYMENT_QUERY_URL:https://gw.open.icbc.com.cn/api/cardbusiness/aggregatepay/b2c/online/orderqry/V1}
    refund-url: ${ICBC_REFUND_URL:https://gw.open.icbc.com.cn/api/cardbusiness/aggregatepay/b2c/online/merrefund/V1}
    refund-query-url: ${ICBC_REFUND_QUERY_URL:https://gw.open.icbc.com.cn/api/cardbusiness/aggregatepay/b2c/online/refundqry/V1}

# 支付默认配置
payment:
  default-expired-seconds: 3600


# 建行惠市宝支付配置
hsb:
  base-url: ${HSB_BASE_URL:http://marketpaypl4.dev.jh:8035/online/direct/}
  mkt-id: ${HSB_MKT_ID:41060860811052}
  private-key: ${HSB_PRIVATE_KEY:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDS9se1wbq51SXw49bZgzIdj/ShiV618b/vNDztFhK/iW1nD1zMxo72YD9yHRX8jVWnrByDwL18107HK2nYbHu8t3Bcxd8k3/tpZgosbDOoXExDuJG02cwSx4jbCK6x5WWvucGO+tjoMaB1pPEurK6R8AVykcEzB6eo0bGSjx6ZUDh3pUESMXTKkXoQO/fJofq1BibWUq5KpAdeNL+yjFUUZg05PH2K7XRFp8nwe9tDQ3HrvUx1HhyNP/IFxU/XSR/D7uZsYuYOehiBX76mQzYD8PocnS0ehjpcyho7R/jmGuD4O6BGdWxCthrNrrRd6g030/TvfRictiuEJAMSQqf/AgMBAAECggEAHa61OMCSSjVQSk10XFRWR8yKafQPDGCAVeKus9kIOETYzMhfkTxavxWZt6+Z+VfVdmsD9BG5V4hfwCw+j0HsQwg4WgVJOUH+eLzvr4Jl3klmPZ0Jez2ttfK3McJN+h/Bp/Dl5/0paboZzpOvj5aiVUxFJ/KUEV8BWwJuDqXuczmRsG/JwXCDnLsrIEMmyBXDgvGSEiu/L6mjfIMNpwBPGkTiiJGRlBSWIAWdQr/jNw/po0zb+jlCVGWoPcivWGAafXJQX66aAk4JMiNCuLjdkH+xen/xSWU/QEQ9nWwLRJh6l9shvPWY3bfqQKPYkDGyyLdIUzxpIQBpkn+SZp5TSQKBgQD7KOtBC0bcVPpOVu333BC/pxMzqA2HPMyflQuUr7Di6HXZulxb2qEuXfafRMgVo7puLu/TDozZa83L7W1nEf5nbjClVEgVMbhT1uNgkIRuJ8CJu50wnDWUBsmMB4+Dn6kUG7YD/Psp4M1xzhWQSXvyxFXzAf6+DzrISK0FymJeVQKBgQDXB462cxKLbot8la1rQIjw2lX6p/WMBASuqOnPFlkDjIZuQbYfXchWxJRXVLCUikPzBLjWvJHbjrhmBTeIyxTyib+JThqaMzyMf0Y77/GiUJdUBx7PFHFyhDaj+jSmOxi7ceSZF37RNn539D2S6E7Qusj3OYPlaQrSV1WmLxBZAwKBgQDh9lSBdnXQMRvpc0gxoOnoo5Yg+WcCbu7h/CQpJ1ALNX0h4ArMEQzGPH9vl2A0J9PI4a2eww5xZg4HFJtDCetKftaBSCx59PuTYle7PwoGWPlecU7gtwl1Hg4iT4MMto5VqwC84dPOP5RWeUTpRVOgfIefVAIuWGFYZBpWhViu6QKBgQDLU3gdCX6VnbgD3DyZV/KlXK9ETyGefgY3ab18djNBadWL2FLwIevYMBXc5lX6fyt1Vhe55aE+LRwsS+6RSQbLuHkGynXZLW2ppIezEVY5F1+gswLs6PXFRUOtll/Gd8cRJ8bzBAaEqbS4lJjMmyI7uQNi0l3nxYXYE4EHnSUmJQKBgHqcrvr0P2fl01Yma4CxU/CVppAWpN2xPFrIaOgIhMRwAIB/VJxMIcA35hjf5IDMFeevGFtqUCMHtxvFeDWsQlFw4WVR3aaATnQypNC3lukH4kgko7v6IsVj0NoaVOJd2kpNmivlcQGNGX1fg+wfkuF2vksKWfsJVZjM8GUoqMiu}
  platform-public-key: ${HSB_PLATFORM_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0vbHtcG6udUl8OPW2YMyHY/0oYletfG/7zQ87RYSv4ltZw9czMaO9mA/ch0V/I1Vp6wcg8C9fNdOxytp2Gx7vLdwXMXfJN/7aWYKLGwzqFxMQ7iRtNnMEseI2wiuseVlr7nBjvrY6DGgdaTxLqyukfAFcpHBMwenqNGxko8emVA4d6VBEjF0ypF6EDv3yaH6tQYm1lKuSqQHXjS/soxVFGYNOTx9iu10RafJ8HvbQ0Nx671MdR4cjT/yBcVP10kfw+7mbGLmDnoYgV++pkM2A/D6HJ0tHoY6XMoaO0f45hrg+DugRnVsQrYaza60XeoNN9P0730YnLYrhCQDEkKn/wIDAQAB}
  version:
    place-order: "5"
    query-order: "5"
    refund-order: "3"
    query-refund: "4"
    confirm-settlement: "4"
  initiator-system-id: "00000"
  initiator-channel-code: "0000000000000000000000000"

# 过期订单定时任务
scheduler:
  payment-expiration: "0 */5 * * * *"
  refund-query: "0 */5 * * * *"
